//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeolocationDnm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geolocation { get; set; }
        public string StreetName { get; set; }
        public string ExtraData { get; set; }
        public long TimeStamp { get; set; }
        public long Accuracy { get; set; }
    }
}
